version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Привязываем порт приложения к локальной машине
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: users_db
    command: ["./main"] # Запуск приложения

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432" # Привязываем порт PostgreSQL к локальной машине
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on: 
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/users_db?sslmode=disable",
      "up"
    ]

volumes:
  db_data:
